CREATE TABLE PARKRUN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    STREET_NAME VARCHAR(255) NOT NULL,
    STREET_NUMBER VARCHAR(10) NOT NULL,
    SUBURB VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    PROVINCE VARCHAR(255) NOT NULL
);